var riddles = [
    {"Question":"It is greater than God and more evil than the devil. The poor have it, the rich need it and if you eat it you'll die. What is it?", "Answer":"nothing"},
    {"Question":"I am the beginning of the end, and the end of time and space. I am essential to creation, and I surround every place. What am I?", "Answer":"e"},
    {"Question":"At night they come without being fetched. By day they are lost without being stolen. What are they?", "Answer":"stars"},
    {"Question":"The one who makes it, sells it. The one who buys it, never uses it. The one that uses it never knows that he's using it. What is it?", "Answer":"coffin"},
    {"Question":"The more you have of it, the less you see. What is it?", "Answer":"darkness"},
    {"Question":"What has a head, a tail, is brown, and has no legs?", "Answer":"penny"},
    {"Question":"I am always hungry, I must always be fed, The finger I touch, will soon turn red.", "Answer":"fire"},
    {"Question":"My life can be measured in hours, I serve by being devoured. Thin, I am quick. Fat, I am slow. Wind is my fo. What am I?", "Answer":"candle"},
    {"Question":"I am seen in the water if seen in the sky. I am in the rainbow, a jay's feather, and lapis lazuli.", "Answer":"blue"},
    {"Question":"Glittering points that downward thrust. Sparkling spears that never rust.", "Answer":"icicle"},
    {"Question":"Two in a corner, 1 in a room, 0 in a house, but 1 in a shelter. What am I?", "Answer":"r"},
    {"Question":"It cannot be seen, it weighs nothing, but when put into a barrel, it makes it lighter. What is it?", "Answer":"hole"},
    {"Question":"What starts with a T, ends with a T, and has T in it?", "Answer":"teapot"},
    {"Question":"A box without hinges, lock or key, yet golden treasure lies within. What is it?", "Answer":"egg"},
    {"Question":"Forward I'm heavy, but backwards I'm not. What am I?", "Answer":"ton"},
    {"Question":"Reaching stiffly for the sky, I bare my fingers when it's cold. In warmth I wear an emerald glove. And in between I dress in gold", "Answer":"tree"},
    {"Question":"My first is twice in apple but not once in tart. My second is in liver but not in heart. My third is in giant and also in ghost. Whole I'm best when I am roast. What am I?", "Answer":"pig"},
    {"Question":"What gets wetter as it dries?", "Answer":"towel"}
];